### ISSUE TITLE
Fix links in README.md

### ISSUE THREAD

**Issue by matyasselmeci** [opensciencegrid/osg-vo-config#40]
The README.md file still links to the TWiki. Fix the links to point to our new docs.

**Comment by edquist** [comment]
Yeah https://twiki.grid.iu.edu/bin/view/Operations/GithubVOPackageUpdate was all the money but it was still in the GOC world order frame of reference, plus we never archived the twiki Operations web.

I still have a copy of it if anybody wants, which i suppose we can use to update our current (out of date) doc.

**Comment by brianhlin** [comment]
If by "we", you mean "you" :) (https://opensciencegrid.atlassian.net/browse/SOFTWARE-3157)

**Comment by matyasselmeci** [comment]
Looks like this is done.
